mccs_addrs = [
    "192.168.211.2",
    "192.168.211.34",
    "192.168.211.66",
    "192.168.211.162",
]
mccs_port = 5000

[[comm_patterns_reconfig]]
communicator_id = 200
channels = [
    { channel_id = 0, ring = [0, 1, 2, 3], udp_sport = [[1, 2, 49202], [3, 0, 49202]], net_dev = "mlx5_0" },
    { channel_id = 1, ring = [0, 1, 2, 3], udp_sport = [[1, 2, 49202], [3, 0, 49202]], net_dev = "mlx5_0" },
]

[[comm_patterns_reconfig]]
communicator_id = 201
channels = [
    { channel_id = 0, ring = [0, 1], udp_sport = [[0, 1, 49200], [1, 0, 49200]], net_dev = "mlx5_0" },
    { channel_id = 1, ring = [0, 1], udp_sport = [[0, 1, 49200], [1, 0, 49200]], net_dev = "mlx5_0" },
]


[[comm_patterns_reconfig]]
communicator_id = 202
channels = [
    { channel_id = 0, ring = [0, 1], udp_sport = [[0, 1, 49200], [1, 0, 49200]], net_dev = "mlx5_0" },
    { channel_id = 1, ring = [0, 1], udp_sport = [[0, 1, 49200], [1, 0, 49200]], net_dev = "mlx5_0" },
]